"""audio-upload

Revision ID: d44abe45f251
Revises: 7fc6d2bfe359
Create Date: 2025-11-18 20:57:11.636713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44abe45f251'
down_revision = '7fc6d2bfe359'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('voice_url', sa.String(), nullable=True))
    op.add_column('chat_history', sa.Column('response_audio_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'response_audio_url')
    op.drop_column('chat_history', 'voice_url')
    # ### end Alembic commands ###

